<h1 align = 'center'> Mini - Batch Gradient Descent </h1>

In [24]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_diabetes
import random

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
X.shape, y.shape

((442, 10), (442,))

#### Train test split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=2)

#### Model Training

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
model.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [11]:
model.intercept_

151.88334520854633

#### Performance metrics

In [12]:
from sklearn.metrics import r2_score

In [13]:
y_pred = model.predict(X_test)
print("r2_score = ", r2_score(y_test,y_pred))

r2_score =  0.4399387660024645


### Class 

In [14]:
X.shape

(442, 10)

In [33]:
class MBGDRegressor:
    
    def __init__ (self,batch_size, learning_rate=0.01, epochs= 100):
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs =epochs
        self.batch_size = batch_size
        
    def fit(self,X_train, y_train):
        #initialize parameters : b=0, b1,b2,---bn = 1
        self.intercept_ = 0 
        
        #X_train shape will tell how many coef are there
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(X_train.shape[0]/ self.batch_size)): 
                # if my batch size is 10 i will select random 10 smaple in loop 
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
            # Update all coef_ and intercept_
            y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_  #y_hat = b + wT.x
            
            intercept_derv = - 2 *np.mean(y_train[idx]-y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_derv)
            
            #update Coef
            coef_derv = -2* np.dot((y_train[idx]- y_hat),X_train[idx])
            self.coef_ = self.coef_ - (self.lr * coef_derv)
            
            
        #print(y_hat.shape)
        print(self.intercept_, self.coef_)
        
        
        
        
        
    
    def predict(self, X_test):
        return np.dot(X_test, self.coef_)+self.intercept_

In [27]:
X_train[[63, 40, 62, 93, 54, 57, 69, 67, 9, 68]].shape # we are selecting 10 rows of X_train

(10, 10)

In [38]:
gd = MBGDRegressor(batch_size=int(X_train.shape[0]/10),learning_rate=0.1,epochs=100)

In [39]:
gd.fit(X_train,y_train) # Initialize 

151.31446331117513 [  46.3135966  -164.02732153  467.09720669  270.81900793  -22.46648923
  -69.38870163 -201.62866693  132.79579493  395.17958698  100.65314859]


In [18]:
gd = GDRegressor(epochs=1000)
gd.fit(X_train,y_train)

151.90197654519747 [  -7.41032246 -200.16617472  533.25518552  338.23799406 -137.42989217
  -52.86615812 -170.28983465   54.54383886  571.24202059   53.64638953]


In [40]:
y_pred = gd.predict(X_test)

In [41]:
r2_score(y_test,y_pred)

0.4597156707548138

### Time taken 

In [42]:
import time

In [44]:
start = time.time()
gd = MBGDRegressor(batch_size=int(X_train.shape[0]/10),learning_rate=0.1,epochs=100)
gd.fit(X_train,y_train)
print("Time take is ", time.time()-start)

153.54352630966014 [  46.58910154 -135.43648263  435.61704688  276.62660133  -17.35894623
  -70.25450519 -208.60239967  132.05071491  395.80836262  109.36475681]
Time take is  0.09089374542236328


### Mini batch using SGD Regressor

In [45]:
from sklearn.linear_model import SGDRegressor

In [52]:
sgd = SGDRegressor(learning_rate='constant',eta0 = 0.1)

In [53]:
batch_size = 35
for _ in range(100):
    idx= random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx]) 

In [54]:
sgd.coef_

array([  56.42648962,  -35.96076095,  337.25409905,  235.44920716,
         16.20107919,  -33.07779072, -168.46529905,  129.63072513,
        314.35793168,  136.62997574])

In [55]:
sgd.intercept_

array([120.9075559])

In [56]:
y_pred=sgd.predict(X_test)

In [57]:
r2_score(y_test,y_pred)

0.24815742634000593